"""
Report Generator Module
Generates HTML reports from analysis results.
"""
import os
from datetime import datetime
from typing import Dict, Any, List, Optional
import pandas as pd

class ReportGenerator:
    """Generates HTML/PDF reports from analysis results."""
    
    def __init__(self, title: str = "Statelix Analysis Report"):
        self.title = title
        self.sections = []
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
    def add_section(self, title: str, content: str, table: Optional[pd.DataFrame] = None):
        """Add a section to the report."""
        self.sections.append({
            'title': title,
            'content': content,
            'table': table
        })
    
    def add_descriptive_stats(self, df: pd.DataFrame):
        """Add descriptive statistics section."""
        desc = df.describe(include='all').round(3)
        self.add_section("Descriptive Statistics", "", desc)
    
    def add_correlation_matrix(self, df: pd.DataFrame):
        """Add correlation matrix section."""
        num_df = df.select_dtypes(include=['number'])
        if not num_df.empty:
            corr = num_df.corr().round(3)
            self.add_section("Correlation Matrix", "", corr)
    
    def add_model_result(self, model_name: str, summary: str, table: Optional[pd.DataFrame] = None):
        """Add model result section."""
        self.add_section(f"Model: {model_name}", summary, table)
    
    def generate_html(self) -> str:
        """Generate HTML report."""
        html = f'''<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{self.title}</title>
    <style>
        body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; background: #f5f5f5; }}
        .container {{ max-width: 900px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
        h1 {{ color: #333; border-bottom: 2px solid #6C5CE7; padding-bottom: 10px; }}
        h2 {{ color: #6C5CE7; margin-top: 30px; }}
        .timestamp {{ color: #666; font-size: 0.9em; }}
        table {{ border-collapse: collapse; width: 100%; margin: 15px 0; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
        th {{ background-color: #6C5CE7; color: white; }}
        tr:nth-child(even) {{ background-color: #f9f9f9; }}
        pre {{ background: #f4f4f4; padding: 15px; border-radius: 5px; overflow-x: auto; }}
        .footer {{ margin-top: 30px; padding-top: 15px; border-top: 1px solid #ddd; color: #666; font-size: 0.85em; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>{self.title}</h1>
        <p class="timestamp">Generated: {self.timestamp}</p>
'''
        
        for section in self.sections:
            html += f'<h2>{section["title"]}</h2>\n'
            if section['content']:
                html += f'<pre>{section["content"]}</pre>\n'
            if section['table'] is not None:
                html += section['table'].to_html(classes='dataframe')
        
        html += '''
        <div class="footer">
            <p>Generated by Statelix - Statistical Analysis Platform</p>
        </div>
    </div>
</body>
</html>'''
        return html
    
    def save(self, filepath: str):
        """Save report to file."""
        html = self.generate_html()
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html)
        return filepath
